import re
from collections import OrderedDict

from parsers.base_parser import BaseParser

from models.report import Report
from models.class_result import ClassResult
from models.test_result import TestResult


class PassedTestsParser(BaseParser):
    """
    Parses passed_tests.txt generated by TradeFed.

    Every discovered test is marked PASS.
    """

    TEST_PATTERN = re.compile(
        r".*?([A-Za-z0-9_$.]+)#([A-Za-z0-9_]+)$"
    )

    def parse(self, file_bytes):

        text = self.decode_file(file_bytes)

        report = Report()

        report.report_type = "tradefed_passed"

        report.suite_name = "TradeFed Passed Tests"

        classes = OrderedDict()

        for line in text.splitlines():

            line = line.strip()

            if not line:
                continue

            match = self.TEST_PATTERN.match(line)

            if not match:
                continue

            full_class = match.group(1)

            function = match.group(2)

            class_name = full_class.split(".")[-1]

            if class_name not in classes:

                classes[class_name] = ClassResult(
                    name=class_name
                )

            test = TestResult(

                name=function,

                classname=class_name,

                status="pass",

                time=0.0,

                message="",

                stacktrace=""

            )

            classes[class_name].add_test(test)

        for cls in classes.values():

            report.add_class(cls)

        report.sort_classes()

        return report
        